# Generated by Django 2.1.5 on 2019-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.IntegerField(primary_key='true', serialize=False)),
                ('country', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('price', models.IntegerField()),
                ('province', models.CharField(max_length=50)),
                ('region_1', models.CharField(max_length=100)),
                ('region_2', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('winery', models.CharField(max_length=100)),
            ],
        ),
    ]
